rel:
	@cd vio;    make
	@cd venc;   make
	@cd region; make
	@cd audio;  make
	@cd ive;    make
	@cd vgs;    make
	@cd scene_auto;    make

clean:
	@cd vio;    make clean
	@cd venc;   make clean
	@cd region; make clean
	@cd audio;  make clean
	@cd ive;    make clean
	@cd vgs;    make clean
	@cd scene_auto;    make clean

cleanall:
	@cd vio;    make clean;   make cleanstream
	@cd venc;   make clean;   make cleanstream
	@cd region; make clean;   make cleanstream
	@cd audio;  make clean;   make cleanstream
	@cd ive;    make clean
	@cd vgs;    make clean;   make cleanstream
