rel:
	@cd hifb;   make
	@cd vio;    make
	@cd rtsp;   make
	@cd venc;   make
	@cd region; make
	@cd vda;    make
	@cd audio;  make
	@cd iq;     make
	@cd tde;    make

clean:
	@cd hifb;   make clean
	@cd vio;    make clean
	@cd rtsp;   make clean
	@cd venc;   make clean
	@cd region; make clean
	@cd vda;    make clean
	@cd audio;  make clean
	@cd iq;     make clean
	@cd tde;    make clean

cleanall:
	@cd hifb;   make clean;   make cleanstream
	@cd vio;    make clean;   make cleanstream
	@cd rtsp;   make clean;   make cleanstream
	@cd venc;   make clean;   make cleanstream
	@cd region; make clean;   make cleanstream
	@cd vda;    make clean;   make cleanstream
	@cd audio;  make clean;   make cleanstream
	@cd iq;     make clean;   make cleanstream
	@cd tde;    make clean